### ISSUE TITLE
Branch revamp's functionality

### ISSUE THREAD

**Issue by eu49** [cornell-zhang/datuner#22]
The relevant files (setup, tune, etc.) are copied to the directory where the tool has been run. But apparently, _setup.py_ is not called by _tune.py_. Therefore no evaluation or tuning is performed, and no global results file is created. @tincanman , you have replaced socket interface with dispy. Are you running the tool the same way we did? Do we need to change the format of [tool].py? It used to consist of the flags, design directory & top module, workspace, machine id, and server address. Thanks.

**Comment by tincanman** [comment]
I don't think I changed the way the tool is ran. What do you mean by [tool].py? Right now, the dispy host calls the tune.py file and the tune.py script should import the methods from setup.py and run them (I believe this is part of the opentuner workflow?).

**Comment by eu49** [comment]
Thanks Tim. By the way, [tool].py is the script that has the design and environment variables, such as custom.py.

**Comment by eu49** [comment]
The problem is resolved with [this commit](https://github.com/cornell-zhang/datuner/commit/c00f8b634dda6992ec28f3b64181100cbf4fe836). The non-sweep mode (i.e. tune mode) was lacking the proper transfer and initiation of dispynode on the servers; and some python module imports were missing.
