### ISSUE TITLE
Bug when integer variable has only two possible values

### ISSUE THREAD

**Issue by zhouyuan1119** [cornell-zhang/datuner#23]
I am trying to tune integer parameters with DATuner. This should be supported since OpenTuner has a way to tune integer parameters:

``manipulator.add_parameter(IntegerParameter("INT_VAR", lower_bound, upper_bound))``

Currently there seems to be no convenient way of specifying integer variables in DATuner. For example, suppose I have an integer variable in the range [8, 15], I have to write something like the following in `custom.py`:

`INTEGER_VARIABLE = [8, 9, 10, 11, 12, 13, 14, 15]`
or
`INTEGER_VARIABLE = range(8, 16)`

Even so, DATuner will treat them as enum variables rather than integer variables. In addition, when the integer variable only has two possible values, if I write in this way DATuner will treat them as **float** variables:

`INTEGER_VARIABLE = [4, 5]` makes DATuner choose a value of 4.39782569795 for this variable.

**Comment by Hecmay** [comment]
Received. It seems the DATuner revamp only returns the manipulator with `EnumParamter` type.
>$DATUNER_HOME/src/tune.py + 33
```
    manipulator = ConfigurationManipulator()
    for item in self.param:
      print item
      param_type, param_name, param_range = item
      if param_type == 'EnumParameter':
        manipulator.add_parameter(EnumParameter(param_name, param_range))
    return manipulator
```
I will update DATuner revamp with support for tuning variable with other different types.
