### ISSUE TITLE
Crash when running DATuner

### ISSUE THREAD

**Issue by zhouyuan1119** [cornell-zhang/datuner#24]
DATuner crashed when I am running on zhang-x1. I am running the custom flow. My script calls _Vivado HLS_ to evaluate different design points. I also installed _scikit-learn_ and _xgboost_ python libraries using _pip_, and some library functions are called inside my script. When I am running the command

`datuner.py -f custom -b 20 -t 1d:0h:0m:0s -p 1`

DATuner crashed after exploring two design points. The issue is reproducable. The complete crashlog is attached.

[datuner_crash_log.txt](https://github.com/cornell-zhang/datuner/files/1878385/datuner_crash_log.txt)

Seems like some memory corruption issue?

**Comment by zhangzhiru** [comment]
Are you using master or revamp?

**Comment by zhouyuan1119** [comment]
I am using master.

**Comment by eu49** [comment]
Custom flow is working. I made some changes for Quartus, and now I'm testing. Then I'll test the other cases under $DATUNER_HOME/flows.
